tuple_turtle = ('T','U','R','T','L','E')
tuple_number = (1,2,3)
tuple_hybird = ('T','U',1,2,)
tuple_only_one = ('Only One Element',)
no_tuple = ("No Tuple")
tuple_list = (["Turtle"],[""],["graphics"])
print("字符元组：",tuple_turtle)
print("数字元组：",tuple_number)
print("混合元组：",tuple_hybird)
print("只有一个元素的元组：",tuple_only_one)
print("没有元组：",no_tuple)
print("列表元组：",tuple_list)